/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AnnotationPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var COMMENT_REGEX = /<span class="ob-comment" data-note="(.*?)">(.*?)<\/span>/g;
var AnnotationPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.tooltipEl = null;
  }
  async onload() {
    this.addCommand({
      id: "add-annotation-html",
      name: "\u6DFB\u52A0\u6279\u6CE8 (HTML)",
      editorCallback: (editor, view) => {
        const selection = editor.getSelection();
        if (!selection) {
          new Notice("\u8BF7\u5148\u9009\u62E9\u4E00\u6BB5\u6587\u672C");
          return;
        }
        new AnnotationModal(this.app, (noteContent) => {
          const safeNote = noteContent.replace(/"/g, "&quot;");
          const replacement = `<span class="ob-comment" data-note="${safeNote}">${selection}</span>`;
          editor.replaceSelection(replacement);
        }).open();
      }
    });
    this.registerEditorExtension(livePreviewAnnotationPlugin);
    this.createTooltipElement();
    this.registerDomEvent(document, "mouseover", (evt) => {
      const target = evt.target;
      if (target && target.hasClass && target.hasClass("ob-comment")) {
        const note = target.getAttribute("data-note");
        if (note) {
          this.showTooltip(evt, note);
        }
      }
    });
    this.registerDomEvent(document, "mouseout", (evt) => {
      const target = evt.target;
      if (target && target.hasClass && target.hasClass("ob-comment")) {
        this.hideTooltip();
      }
    });
  }
  onunload() {
    if (this.tooltipEl) {
      this.tooltipEl.remove();
    }
  }
  // --- Tooltip 相关逻辑 ---
  createTooltipElement() {
    this.tooltipEl = document.body.createDiv({ cls: "ob-annotation-tooltip" });
  }
  showTooltip(evt, text) {
    if (!this.tooltipEl) return;
    this.tooltipEl.innerText = text;
    this.tooltipEl.addClass("is-visible");
    const x = evt.pageX;
    const y = evt.pageY - 40;
    this.tooltipEl.style.left = `${x}px`;
    this.tooltipEl.style.top = `${y}px`;
  }
  hideTooltip() {
    if (!this.tooltipEl) return;
    this.tooltipEl.removeClass("is-visible");
  }
};
var AnnotationModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u8F93\u5165\u6279\u6CE8\u5185\u5BB9" });
    const inputEl = contentEl.createEl("textarea", {
      cls: "annotation-input",
      attr: { rows: "3", style: "width: 100%; margin-bottom: 10px;" }
    });
    inputEl.focus();
    inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
        e.preventDefault();
        this.submit(inputEl.value);
      }
    });
    const btnContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const submitBtn = btnContainer.createEl("button", { text: "\u786E\u5B9A", cls: "mod-cta" });
    submitBtn.addEventListener("click", () => {
      this.submit(inputEl.value);
    });
  }
  submit(value) {
    this.onSubmit(value);
    this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var livePreviewAnnotationPlugin = import_view.ViewPlugin.fromClass(class {
  constructor(view) {
    this.decorations = this.buildDecorations(view);
  }
  update(update) {
    if (update.docChanged || update.viewportChanged || update.selectionSet) {
      this.decorations = this.buildDecorations(update.view);
    }
  }
  buildDecorations(view) {
    const builder = new import_state.RangeSetBuilder();
    const text = view.state.doc.toString();
    const selection = view.state.selection.main;
    const cursorFrom = selection.from;
    const cursorTo = selection.to;
    let match;
    COMMENT_REGEX.lastIndex = 0;
    while ((match = COMMENT_REGEX.exec(text)) !== null) {
      const fullMatch = match[0];
      const noteContent = match[1];
      const visibleText = match[2];
      const startPos = match.index;
      const endPos = startPos + fullMatch.length;
      const openingTagLength = fullMatch.indexOf(">") + 1;
      const openingTagFrom = startPos;
      const openingTagTo = startPos + openingTagLength;
      const contentFrom = openingTagTo;
      const contentTo = contentFrom + visibleText.length;
      const closingTagFrom = contentTo;
      const closingTagTo = endPos;
      const isCursorInside = cursorFrom >= startPos && cursorFrom <= endPos || cursorTo >= startPos && cursorTo <= endPos;
      if (isCursorInside) {
        continue;
      }
      builder.add(
        openingTagFrom,
        openingTagTo,
        import_view.Decoration.replace({})
        // replace为空，即隐藏
      );
      builder.add(
        contentFrom,
        contentTo,
        import_view.Decoration.mark({
          class: "ob-comment",
          // 使用 CSS 中定义的样式
          attributes: { "data-note": noteContent }
          // 把批注内容加上，方便鼠标事件获取
        })
      );
      builder.add(
        closingTagFrom,
        closingTagTo,
        import_view.Decoration.replace({})
        // replace为空，即隐藏
      );
    }
    return builder.finish();
  }
}, {
  decorations: (v) => v.decorations
});
